### ISSUE TITLE
Not deploying

### ISSUE THREAD

**Issue by quinnjax1** [CyberTitus/P45#1]
Ive tried to run the proxy multiple times but it keeps saying that it wont deploy.

**Comment by AbdulRKB** [comment]
Please can you provide a screenshot of the error?

**Comment by quinnjax1** [comment]
![Screenshot 2023-05-25 3 40 43 PM](https://github.com/CyberTitus/P45/assets/134561556/ea8893c1-3d7a-496f-950c-d493825983ff)

**Comment by AbdulRKB** [comment]
Hello, I've just tried hosting the site myself and it perfectly worked. I think you are misconfiguring the webapp.

Here is a tutorial (video expires in 2 days): [streamable.com/f31ozq](https://streamable.com/f31ozq)


Please inform if it still doesn't work.

**Comment by AbdulRKB** [comment]
did it work?
